### ISSUE TITLE
How to use this program?

### ISSUE THREAD

**Issue by shuge** [andrewzwicky/PUBGIS#1]
Launch it after start play game?  pass some arguments?

**Comment by andrewzwicky** [comment]
Right now, this program is command line, but I'm actively working on the GUI.  This doesn't work on live gameplay, only recorded videos (.mp4 format).

All that should be needed to run the program is to run:
`pubgis.py --video_file VIDEO_FILE_HERE.mp4`

to see the full list of arguments, type:
`pubgis.py --help`

FYI the program requires:
python 3.6+
opencv
matplotlib

**Comment by shuge** [comment]
>only recorded videos 
What tool could records game, any recommandeds?

**Comment by andrewzwicky** [comment]
try https://obsproject.com/, use the .mp4 format for the best results
