### ISSUE TITLE
GUI startup very slow

### ISSUE THREAD

**Issue by andrewzwicky** [andrewzwicky/PUBGIS#12]
Because there are class attributes that are very slow, these are run when the modules are imported, rather than the first time they are used.  I think this causes the GUI to be very slow starting up.

https://github.com/andrewzwicky/PUBGIS/blob/2068f62e7a4fb1124496c7ba3720d63093e371ef/pubgis/match.py#L54-L60

**Comment by andrewzwicky** [comment]
The branch being released in be3f4515f2ce9aabca3be59920e2442e7f6ec3af reduces this because there is less map copying happening, especially on startup.  Can re-open if it's a big issue still.

**Comment by handrake** [comment]
I think I'm experiencing this issue. GUI startup takes about ~5 sec with the latest executable before I see the first menu.
