### ISSUE TITLE
Add support for other resolutions

### ISSUE THREAD

**Issue by andrewzwicky** [andrewzwicky/PUBGIS#14]
Currently, only 1920x1080 is supported and minimap locations are hard-coded.  Need to determine minimap locations for other resolutions and include those.

**Comment by andrewzwicky** [comment]
https://github.com/andrewzwicky/PUBGIS/blob/bc61c6d8f4845480a52bf163d01e7359cb46e562/pubgis/match.py#L140-L153

Changes will need to happen here as well.  Currently, the world map is scaled to match up with 1920x1080, so if other resolutions are used, that will need to be scaled to match that resolution so the template matching works properly.

Additionally, the mask files should be scaled as well (this should be simpler).

**Comment by BiffJutsu** [comment]
Would the screen scaling setting in game mess with this?

**Comment by andrewzwicky** [comment]
Not sure, I don't exactly know what that does.  I tend to doubt it, unless that actually physically moves the minimap position on the screen.

**Comment by andrewzwicky** [comment]
For anyone looking for additional resolution support, please send me a screenshot of PUBG running in your resolution.  This will help speed up support for those other resolutions.  Here are the screenshots I have so far:

- [ ] 1024×576
- [ ] 1024×768
- [ ] 1152×648
- [ ] 1280×720
- [ ] 1280×960
- [ ] 1280×800
- [ ] 1366×768
- [ ] 1440×900
- [ ] 1400×1050
- [ ] 1440×1080
- [ ] 1600×900
- [ ] 1600×1200
- [ ] 1680×1050
- [ ] 1856×1392
- [X] 1920×1080
- [ ] 1920×1200
- [ ] 1920×1440
- [ ] 2048×1536
- [X] 2560×1440
- [ ] 2560×1600
- [ ] 3840×2160

**Comment by andrewzwicky** [comment]
resolution_support branch (fb48677e40d43db39f438d9d10cf9d71a7dc0ec1) introduced support for resolution switching.  Currently, the resolutions above are added.  New resolutions added as they are needed. v0.1.4 released with this new functionality
