### ISSUE TITLE
Reduce live mode overhead

### ISSUE THREAD

**Issue by andrewzwicky** [andrewzwicky/PUBGIS#17]
Currently, live mode is set to take a screenshot as quickly as it can.  A small wait should be introduced to reduce CPU loading.

**Comment by BiffJutsu** [comment]
This should be a settable resolution parameter in the UI, some kind of slide bar or something.  I'll probably take a look at this later.

Some data about how quickly most installations are taking pictures would be useful as it would give us an idea about how that rate affects the path display.

**Comment by andrewzwicky** [comment]
Yeah I currently don't have any data regarding this, but it could mirror the time_step selector from the video side.
