### ISSUE TITLE
How do you run PUBGIS?

### ISSUE THREAD

**Issue by handrake** [andrewzwicky/PUBGIS#2]
C:\project\PUBGIS>python pubgis/pubgis_gui.py
Traceback (most recent call last):
  File "pubgis/pubgis_gui.py", line 11, in <module>
    from pubgis.pubgis_color import Color, ColorSpace, ColorScaling
ModuleNotFoundError: No module named 'pubgis'

I can't seem to locate pubgis.py anywhere.

**Comment by andrewzwicky** [comment]
Sorry for the delay.  I've been updating things very quickly.  From my latest push, you should be able to navigate to the PUBGIS repo folder and run `python -m pubgis` to get the gui to appear.

Things are very unpolished right now, and I only have 1920x1080 video set up.  Let me know how it works for you!
