### ISSUE TITLE
Merge functionality from github.com/AMGitsKriss/Battlegrounds

### ISSUE THREAD

**Issue by cspital** [andrewzwicky/PUBGIS#20]
Add in the ability to pull kill feed information and construct node graphs relating inter-player activity to position on the map.

Information could be integrated to:

- Include bubbles at positions where kills happened.
- Produce a graphviz graphic about the match's kill events.

**Comment by AMGitsKriss** [comment]
Will have a closer look at this when I have a bit of time. Worth noting that if a player leaves the match before it ends, the trees will be incomplete.

**Comment by andrewzwicky** [comment]
Just FYI kill feed stuff is definitely welcome if it's path or location related, but I'd prefer not to just merge in a bunch of entirely unrelated functionality.  Do you more details about what exactly you'd be looking to do?

**Comment by BiffJutsu** [comment]
Understood, adding context to a player's location by seeing what information about that player is in the kill feed.

- red x for downed
- skull for killed
- gun for kill other player

Something along those lines.
