### ISSUE TITLE
Wrong export map. 

### ISSUE THREAD

**Issue by football13tb** [andrewzwicky/PUBGIS#21]
Simply put, your program is using an outdated map to export the file. The new map has an entirely new city in it called Kameshki in the NE of map and they added 15+ little compounds on the map.

**Comment by andrewzwicky** [comment]
Definitely.  If anyone knows how to extract the map from the game files, please let me know.  I found the old one on a forum that has lots of cheats floating around, so if I can get it myself, I prefer that.

**Comment by Captnwalker1** [comment]
http://www.gildor.org/en/projects/umodel

Load up the PAK directory in tslGame/Content/Paks

Check flat view in the top left, in the filter type in Erangel_minimap, double click it, it may ask about version, I did 4.14 and it worked, then goto tools and export, then look in the UI/HUD folder. It is a high res TGA file, pick your editor, free paint.net can open.

**Comment by andrewzwicky** [comment]
@Captnwalker1 thank you so much, that's exactly what I needed
