### ISSUE TITLE
pip dependencies on OSX

### ISSUE THREAD

**Issue by dabroz** [andrewzwicky/PUBGIS#23]
I've installed PUBGIS using

```
brew install python3
pip3.6 install pubgis
```

but was unable to run it without manually installing all packages:

```
pip3.6 install pyqt5
pip3.6 install opencv-python
pip3.6 install matplotlib
```

**Comment by andrewzwicky** [comment]
Several commits to fix this issue, should be resolved in 52f85187a231c06d398308c000d50abb0f56c24d.  v0.1.5 should resolve this issue.
