### ISSUE TITLE
failed to execute script__main__ in v0.2.2 on startup

### ISSUE THREAD

**Issue by Perpetucake** [andrewzwicky/PUBGIS#39]
title

**Comment by andrewzwicky** [comment]
I'm going to need more information than that.

What were you trying to do when the error occured?  Do you have a traceback?

**Comment by Perpetucake** [comment]
Just opening the program fails, only with the newest version.

**Comment by andrewzwicky** [comment]
Got it now, should have a fix in a few minutes.  Thanks for the report.

**Comment by andrewzwicky** [comment]
Fixed in 493aadb78fad2e58fb76e2e634a63d9997373ec2, v0.2.3 building now
