### ISSUE TITLE
Intermittent crashes when running

### ISSUE THREAD

**Issue by andrewzwicky** [andrewzwicky/PUBGIS#8]
Experiencing random crashes when processing videos

occurring in c272c04c2ad0fcbbed81a1849a8377ab71b73b09

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	python.exe
  Application Version:	3.6.2150.1013
  Application Timestamp:	596066ed
  Fault Module Name:	Qt5Gui.dll
  Fault Module Version:	5.9.1.0
  Fault Module Timestamp:	59532e82
  Exception Code:	c0000005
  Exception Offset:	000000000001a400
  OS Version:	6.2.9200.2.0.0.768.101
  Locale ID:	1033
  Additional Information 1:	8f7d
  Additional Information 2:	8f7dc64236d5b285d632107ee6cef687
  Additional Information 3:	3444
  Additional Information 4:	344463f0d27c9b5a74dbb16607e4aa7a

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=190175

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
```

Thought the issue was a multiprocessing issue, so adding the RLock in 7f61f168fbef10e2386ee6eabe678877a3849066 would resolve it.  Doesn't seem to have fixed it.

**Comment by andrewzwicky** [comment]
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	python.exe
  Application Version:	3.6.2150.1013
  Application Timestamp:	596066ed
  Fault Module Name:	Qt5Gui.dll
  Fault Module Version:	5.9.1.0
  Fault Module Timestamp:	59532e82
  Exception Code:	c0000005
  Exception Offset:	000000000001a400
  OS Version:	6.2.9200.2.0.0.768.101
  Locale ID:	1033
  Additional Information 1:	8f7d
  Additional Information 2:	8f7dc64236d5b285d632107ee6cef687
  Additional Information 3:	3444
  Additional Information 4:	344463f0d27c9b5a74dbb16607e4aa7a

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=190175

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
```

**Comment by andrewzwicky** [comment]
https://stackoverflow.com/a/17169463/2597564

> Exception code c0000005 is the code for an access violation. That means that your program is accessing (either reading or writing) a memory address to which it does not have rights. Most commonly this is caused by

**Comment by handrake** [comment]
I don't know if this is related,  but I've been experiencing crashes in 3789294 (even after 07b56d1) and no crash report or anything. I'm using Intel 7700k so 8 cores. (this might have something to do with it) If I set the number of cores back to 4, it disappears.

**Comment by andrewzwicky** [comment]
Using 3 cores of my 4 core machine:

Running without the GUI *does not* crash:
```
import cv2

from pubgis.match import PUBGISMatch
from pubgis.video_iterator import VideoIterator

if __name__ == "__main__":
    v = VideoIterator(video_file=r"E:\Movies\OBS\video.mp4")
    m = PUBGISMatch(minimap_iterator=v)
    for p, mini in m.process_match():
        s,_,_ = mini.shape
        cv2.imshow("test", cv2.resize(mini, (0,0), fx=600/s, fy=600/s))
        cv2.waitKey(10)

```

Running the GUI with the same video *crashes*:
```
import sys

from PyQt5.QtWidgets import QApplication

from pubgis.gui import PUBGISMainWindow

if __name__ == "__main__":
    APP = QApplication(sys.argv)
    WIN = PUBGISMainWindow()
    sys.exit(APP.exec_())
```

So it seems to be QThread related.

**Comment by andrewzwicky** [comment]
@handrake It was most likely introduced in 99de1742b39b52a211ef2e1eda74fe05117004e3, but I haven't verified that yet.

**Comment by andrewzwicky** [comment]
Commenting the following lines removes the crashes (so far):

https://github.com/andrewzwicky/PUBGIS/blob/30c8eee13416efc9f5bef8aa79865c0990cb73ea/pubgis/gui.py#L37

https://github.com/andrewzwicky/PUBGIS/blob/30c8eee13416efc9f5bef8aa79865c0990cb73ea/pubgis/gui.py#L50

**Comment by handrake** [comment]
The crash did disappear for me as well.
